// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-payment-aggregator/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentGateway creates a new instance of MockPaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentGateway {
	mock := &MockPaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentGateway is an autogenerated mock type for the PaymentGateway type
type MockPaymentGateway struct {
	mock.Mock
}

type MockPaymentGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentGateway) EXPECT() *MockPaymentGateway_Expecter {
	return &MockPaymentGateway_Expecter{mock: &_m.Mock}
}

// CheckStatus provides a mock function for the type MockPaymentGateway
func (_mock *MockPaymentGateway) CheckStatus(orderID string) (string, error) {
	ret := _mock.Called(orderID)

	if len(ret) == 0 {
		panic("no return value specified for CheckStatus")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(orderID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentGateway_CheckStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckStatus'
type MockPaymentGateway_CheckStatus_Call struct {
	*mock.Call
}

// CheckStatus is a helper method to define mock.On call
//   - orderID string
func (_e *MockPaymentGateway_Expecter) CheckStatus(orderID interface{}) *MockPaymentGateway_CheckStatus_Call {
	return &MockPaymentGateway_CheckStatus_Call{Call: _e.mock.On("CheckStatus", orderID)}
}

func (_c *MockPaymentGateway_CheckStatus_Call) Run(run func(orderID string)) *MockPaymentGateway_CheckStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPaymentGateway_CheckStatus_Call) Return(s string, err error) *MockPaymentGateway_CheckStatus_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPaymentGateway_CheckStatus_Call) RunAndReturn(run func(orderID string) (string, error)) *MockPaymentGateway_CheckStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePayment provides a mock function for the type MockPaymentGateway
func (_mock *MockPaymentGateway) CreatePayment(tx *domain.CreatePaymentRequest) (*domain.PaymentResponse, error) {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *domain.PaymentResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*domain.CreatePaymentRequest) (*domain.PaymentResponse, error)); ok {
		return returnFunc(tx)
	}
	if returnFunc, ok := ret.Get(0).(func(*domain.CreatePaymentRequest) *domain.PaymentResponse); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*domain.CreatePaymentRequest) error); ok {
		r1 = returnFunc(tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentGateway_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockPaymentGateway_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - tx *domain.CreatePaymentRequest
func (_e *MockPaymentGateway_Expecter) CreatePayment(tx interface{}) *MockPaymentGateway_CreatePayment_Call {
	return &MockPaymentGateway_CreatePayment_Call{Call: _e.mock.On("CreatePayment", tx)}
}

func (_c *MockPaymentGateway_CreatePayment_Call) Run(run func(tx *domain.CreatePaymentRequest)) *MockPaymentGateway_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.CreatePaymentRequest
		if args[0] != nil {
			arg0 = args[0].(*domain.CreatePaymentRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPaymentGateway_CreatePayment_Call) Return(paymentResponse *domain.PaymentResponse, err error) *MockPaymentGateway_CreatePayment_Call {
	_c.Call.Return(paymentResponse, err)
	return _c
}

func (_c *MockPaymentGateway_CreatePayment_Call) RunAndReturn(run func(tx *domain.CreatePaymentRequest) (*domain.PaymentResponse, error)) *MockPaymentGateway_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchantRepository creates a new instance of MockMerchantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantRepository {
	mock := &MockMerchantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMerchantRepository is an autogenerated mock type for the MerchantRepository type
type MockMerchantRepository struct {
	mock.Mock
}

type MockMerchantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchantRepository) EXPECT() *MockMerchantRepository_Expecter {
	return &MockMerchantRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMerchantRepository
func (_mock *MockMerchantRepository) Create(ctx context.Context, m *domain.Merchant) (*domain.Merchant, error) {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Merchant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Merchant) (*domain.Merchant, error)); ok {
		return returnFunc(ctx, m)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Merchant) *domain.Merchant); ok {
		r0 = returnFunc(ctx, m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Merchant) error); ok {
		r1 = returnFunc(ctx, m)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMerchantRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *domain.Merchant
func (_e *MockMerchantRepository_Expecter) Create(ctx interface{}, m interface{}) *MockMerchantRepository_Create_Call {
	return &MockMerchantRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockMerchantRepository_Create_Call) Run(run func(ctx context.Context, m *domain.Merchant)) *MockMerchantRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Merchant
		if args[1] != nil {
			arg1 = args[1].(*domain.Merchant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantRepository_Create_Call) Return(merchant *domain.Merchant, err error) *MockMerchantRepository_Create_Call {
	_c.Call.Return(merchant, err)
	return _c
}

func (_c *MockMerchantRepository_Create_Call) RunAndReturn(run func(ctx context.Context, m *domain.Merchant) (*domain.Merchant, error)) *MockMerchantRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByApiKey provides a mock function for the type MockMerchantRepository
func (_mock *MockMerchantRepository) FindByApiKey(ctx context.Context, apiKey string) (*domain.Merchant, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for FindByApiKey")
	}

	var r0 *domain.Merchant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Merchant, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Merchant); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantRepository_FindByApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByApiKey'
type MockMerchantRepository_FindByApiKey_Call struct {
	*mock.Call
}

// FindByApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *MockMerchantRepository_Expecter) FindByApiKey(ctx interface{}, apiKey interface{}) *MockMerchantRepository_FindByApiKey_Call {
	return &MockMerchantRepository_FindByApiKey_Call{Call: _e.mock.On("FindByApiKey", ctx, apiKey)}
}

func (_c *MockMerchantRepository_FindByApiKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockMerchantRepository_FindByApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantRepository_FindByApiKey_Call) Return(merchant *domain.Merchant, err error) *MockMerchantRepository_FindByApiKey_Call {
	_c.Call.Return(merchant, err)
	return _c
}

func (_c *MockMerchantRepository_FindByApiKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) (*domain.Merchant, error)) *MockMerchantRepository_FindByApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockMerchantRepository
func (_mock *MockMerchantRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Merchant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Merchant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Merchant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Merchant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockMerchantRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockMerchantRepository_FindByID_Call {
	return &MockMerchantRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockMerchantRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantRepository_FindByID_Call) Return(merchant *domain.Merchant, err error) *MockMerchantRepository_FindByID_Call {
	_c.Call.Return(merchant, err)
	return _c
}

func (_c *MockMerchantRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Merchant, error)) *MockMerchantRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateApiKey provides a mock function for the type MockMerchantRepository
func (_mock *MockMerchantRepository) RegenerateApiKey(ctx context.Context, id uuid.UUID, newApiKey string) error {
	ret := _mock.Called(ctx, id, newApiKey)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateApiKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, newApiKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMerchantRepository_RegenerateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateApiKey'
type MockMerchantRepository_RegenerateApiKey_Call struct {
	*mock.Call
}

// RegenerateApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - newApiKey string
func (_e *MockMerchantRepository_Expecter) RegenerateApiKey(ctx interface{}, id interface{}, newApiKey interface{}) *MockMerchantRepository_RegenerateApiKey_Call {
	return &MockMerchantRepository_RegenerateApiKey_Call{Call: _e.mock.On("RegenerateApiKey", ctx, id, newApiKey)}
}

func (_c *MockMerchantRepository_RegenerateApiKey_Call) Run(run func(ctx context.Context, id uuid.UUID, newApiKey string)) *MockMerchantRepository_RegenerateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMerchantRepository_RegenerateApiKey_Call) Return(err error) *MockMerchantRepository_RegenerateApiKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMerchantRepository_RegenerateApiKey_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, newApiKey string) error) *MockMerchantRepository_RegenerateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMerchantRepository
func (_mock *MockMerchantRepository) Update(ctx context.Context, m *domain.Merchant) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Merchant) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMerchantRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMerchantRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - m *domain.Merchant
func (_e *MockMerchantRepository_Expecter) Update(ctx interface{}, m interface{}) *MockMerchantRepository_Update_Call {
	return &MockMerchantRepository_Update_Call{Call: _e.mock.On("Update", ctx, m)}
}

func (_c *MockMerchantRepository_Update_Call) Run(run func(ctx context.Context, m *domain.Merchant)) *MockMerchantRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Merchant
		if args[1] != nil {
			arg1 = args[1].(*domain.Merchant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantRepository_Update_Call) Return(err error) *MockMerchantRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMerchantRepository_Update_Call) RunAndReturn(run func(ctx context.Context, m *domain.Merchant) error) *MockMerchantRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMerchantUC creates a new instance of MockMerchantUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchantUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchantUC {
	mock := &MockMerchantUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMerchantUC is an autogenerated mock type for the MerchantUC type
type MockMerchantUC struct {
	mock.Mock
}

type MockMerchantUC_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchantUC) EXPECT() *MockMerchantUC_Expecter {
	return &MockMerchantUC_Expecter{mock: &_m.Mock}
}

// GetProfile provides a mock function for the type MockMerchantUC
func (_mock *MockMerchantUC) GetProfile(ctx context.Context, id uuid.UUID) (*domain.Merchant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *domain.Merchant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Merchant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Merchant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantUC_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type MockMerchantUC_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantUC_Expecter) GetProfile(ctx interface{}, id interface{}) *MockMerchantUC_GetProfile_Call {
	return &MockMerchantUC_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, id)}
}

func (_c *MockMerchantUC_GetProfile_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantUC_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantUC_GetProfile_Call) Return(merchant *domain.Merchant, err error) *MockMerchantUC_GetProfile_Call {
	_c.Call.Return(merchant, err)
	return _c
}

func (_c *MockMerchantUC_GetProfile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Merchant, error)) *MockMerchantUC_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateApiKey provides a mock function for the type MockMerchantUC
func (_mock *MockMerchantUC) RegenerateApiKey(ctx context.Context, id uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateApiKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantUC_RegenerateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateApiKey'
type MockMerchantUC_RegenerateApiKey_Call struct {
	*mock.Call
}

// RegenerateApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockMerchantUC_Expecter) RegenerateApiKey(ctx interface{}, id interface{}) *MockMerchantUC_RegenerateApiKey_Call {
	return &MockMerchantUC_RegenerateApiKey_Call{Call: _e.mock.On("RegenerateApiKey", ctx, id)}
}

func (_c *MockMerchantUC_RegenerateApiKey_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockMerchantUC_RegenerateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantUC_RegenerateApiKey_Call) Return(s string, err error) *MockMerchantUC_RegenerateApiKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMerchantUC_RegenerateApiKey_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (string, error)) *MockMerchantUC_RegenerateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockMerchantUC
func (_mock *MockMerchantUC) Register(ctx context.Context, req *domain.RegisterMerchantRequest) (*domain.Merchant, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *domain.Merchant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RegisterMerchantRequest) (*domain.Merchant, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RegisterMerchantRequest) *domain.Merchant); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.RegisterMerchantRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantUC_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockMerchantUC_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.RegisterMerchantRequest
func (_e *MockMerchantUC_Expecter) Register(ctx interface{}, req interface{}) *MockMerchantUC_Register_Call {
	return &MockMerchantUC_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockMerchantUC_Register_Call) Run(run func(ctx context.Context, req *domain.RegisterMerchantRequest)) *MockMerchantUC_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RegisterMerchantRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.RegisterMerchantRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantUC_Register_Call) Return(merchant *domain.Merchant, err error) *MockMerchantUC_Register_Call {
	_c.Call.Return(merchant, err)
	return _c
}

func (_c *MockMerchantUC_Register_Call) RunAndReturn(run func(ctx context.Context, req *domain.RegisterMerchantRequest) (*domain.Merchant, error)) *MockMerchantUC_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockMerchantUC
func (_mock *MockMerchantUC) UpdateProfile(ctx context.Context, id uuid.UUID, req *domain.UpdateMerchantRequest) (*domain.Merchant, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *domain.Merchant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateMerchantRequest) (*domain.Merchant, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateMerchantRequest) *domain.Merchant); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateMerchantRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantUC_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockMerchantUC_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req *domain.UpdateMerchantRequest
func (_e *MockMerchantUC_Expecter) UpdateProfile(ctx interface{}, id interface{}, req interface{}) *MockMerchantUC_UpdateProfile_Call {
	return &MockMerchantUC_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, id, req)}
}

func (_c *MockMerchantUC_UpdateProfile_Call) Run(run func(ctx context.Context, id uuid.UUID, req *domain.UpdateMerchantRequest)) *MockMerchantUC_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.UpdateMerchantRequest
		if args[2] != nil {
			arg2 = args[2].(*domain.UpdateMerchantRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMerchantUC_UpdateProfile_Call) Return(merchant *domain.Merchant, err error) *MockMerchantUC_UpdateProfile_Call {
	_c.Call.Return(merchant, err)
	return _c
}

func (_c *MockMerchantUC_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, req *domain.UpdateMerchantRequest) (*domain.Merchant, error)) *MockMerchantUC_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateApiKey provides a mock function for the type MockMerchantUC
func (_mock *MockMerchantUC) ValidateApiKey(ctx context.Context, apiKey string) (*domain.Merchant, error) {
	ret := _mock.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for ValidateApiKey")
	}

	var r0 *domain.Merchant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Merchant, error)); ok {
		return returnFunc(ctx, apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Merchant); ok {
		r0 = returnFunc(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Merchant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchantUC_ValidateApiKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateApiKey'
type MockMerchantUC_ValidateApiKey_Call struct {
	*mock.Call
}

// ValidateApiKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *MockMerchantUC_Expecter) ValidateApiKey(ctx interface{}, apiKey interface{}) *MockMerchantUC_ValidateApiKey_Call {
	return &MockMerchantUC_ValidateApiKey_Call{Call: _e.mock.On("ValidateApiKey", ctx, apiKey)}
}

func (_c *MockMerchantUC_ValidateApiKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockMerchantUC_ValidateApiKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchantUC_ValidateApiKey_Call) Return(merchant *domain.Merchant, err error) *MockMerchantUC_ValidateApiKey_Call {
	_c.Call.Return(merchant, err)
	return _c
}

func (_c *MockMerchantUC_ValidateApiKey_Call) RunAndReturn(run func(ctx context.Context, apiKey string) (*domain.Merchant, error)) *MockMerchantUC_ValidateApiKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Create(ctx context.Context, tx *domain.Transaction) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Transaction) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Transaction) *domain.Transaction); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Transaction) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, tx interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, tx *domain.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(*domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(transaction *domain.Transaction, err error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, tx *domain.Transaction) (*domain.Transaction, error)) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOrderID provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) FindByOrderID(ctx context.Context, orderID string) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for FindByOrderID")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Transaction); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_FindByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOrderID'
type MockTransactionRepository_FindByOrderID_Call struct {
	*mock.Call
}

// FindByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockTransactionRepository_Expecter) FindByOrderID(ctx interface{}, orderID interface{}) *MockTransactionRepository_FindByOrderID_Call {
	return &MockTransactionRepository_FindByOrderID_Call{Call: _e.mock.On("FindByOrderID", ctx, orderID)}
}

func (_c *MockTransactionRepository_FindByOrderID_Call) Run(run func(ctx context.Context, orderID string)) *MockTransactionRepository_FindByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_FindByOrderID_Call) Return(transaction *domain.Transaction, err error) *MockTransactionRepository_FindByOrderID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_FindByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*domain.Transaction, error)) *MockTransactionRepository_FindByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Get(ctx context.Context, id uuid.UUID) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTransactionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionRepository_Expecter) Get(ctx interface{}, id interface{}) *MockTransactionRepository_Get_Call {
	return &MockTransactionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTransactionRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Get_Call) Return(transaction *domain.Transaction, err error) *MockTransactionRepository_Get_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Transaction, error)) *MockTransactionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTransactionRepository
func (_mock *MockTransactionRepository) Update(ctx context.Context, tx *domain.Transaction) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Transaction) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Transaction) *domain.Transaction); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Transaction) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Update(ctx interface{}, tx interface{}) *MockTransactionRepository_Update_Call {
	return &MockTransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, tx)}
}

func (_c *MockTransactionRepository_Update_Call) Run(run func(ctx context.Context, tx *domain.Transaction)) *MockTransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Transaction
		if args[1] != nil {
			arg1 = args[1].(*domain.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRepository_Update_Call) Return(transaction *domain.Transaction, err error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionRepository_Update_Call) RunAndReturn(run func(ctx context.Context, tx *domain.Transaction) (*domain.Transaction, error)) *MockTransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionUC creates a new instance of MockTransactionUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionUC {
	mock := &MockTransactionUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionUC is an autogenerated mock type for the TransactionUC type
type MockTransactionUC struct {
	mock.Mock
}

type MockTransactionUC_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionUC) EXPECT() *MockTransactionUC_Expecter {
	return &MockTransactionUC_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTransactionUC
func (_mock *MockTransactionUC) Create(ctx context.Context, merchantID uuid.UUID, req *domain.CreateTransactionRequest) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, merchantID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.CreateTransactionRequest) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, merchantID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.CreateTransactionRequest) *domain.Transaction); ok {
		r0 = returnFunc(ctx, merchantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.CreateTransactionRequest) error); ok {
		r1 = returnFunc(ctx, merchantID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionUC_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionUC_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantID uuid.UUID
//   - req *domain.CreateTransactionRequest
func (_e *MockTransactionUC_Expecter) Create(ctx interface{}, merchantID interface{}, req interface{}) *MockTransactionUC_Create_Call {
	return &MockTransactionUC_Create_Call{Call: _e.mock.On("Create", ctx, merchantID, req)}
}

func (_c *MockTransactionUC_Create_Call) Run(run func(ctx context.Context, merchantID uuid.UUID, req *domain.CreateTransactionRequest)) *MockTransactionUC_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.CreateTransactionRequest
		if args[2] != nil {
			arg2 = args[2].(*domain.CreateTransactionRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTransactionUC_Create_Call) Return(transaction *domain.Transaction, err error) *MockTransactionUC_Create_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionUC_Create_Call) RunAndReturn(run func(ctx context.Context, merchantID uuid.UUID, req *domain.CreateTransactionRequest) (*domain.Transaction, error)) *MockTransactionUC_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTransactionUC
func (_mock *MockTransactionUC) Get(ctx context.Context, id uuid.UUID) (*domain.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionUC_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTransactionUC_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTransactionUC_Expecter) Get(ctx interface{}, id interface{}) *MockTransactionUC_Get_Call {
	return &MockTransactionUC_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockTransactionUC_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTransactionUC_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionUC_Get_Call) Return(transaction *domain.Transaction, err error) *MockTransactionUC_Get_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockTransactionUC_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Transaction, error)) *MockTransactionUC_Get_Call {
	_c.Call.Return(run)
	return _c
}

// HandleNotification provides a mock function for the type MockTransactionUC
func (_mock *MockTransactionUC) HandleNotification(ctx context.Context, req *domain.UpdateStatusRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleNotification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.UpdateStatusRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionUC_HandleNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleNotification'
type MockTransactionUC_HandleNotification_Call struct {
	*mock.Call
}

// HandleNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.UpdateStatusRequest
func (_e *MockTransactionUC_Expecter) HandleNotification(ctx interface{}, req interface{}) *MockTransactionUC_HandleNotification_Call {
	return &MockTransactionUC_HandleNotification_Call{Call: _e.mock.On("HandleNotification", ctx, req)}
}

func (_c *MockTransactionUC_HandleNotification_Call) Run(run func(ctx context.Context, req *domain.UpdateStatusRequest)) *MockTransactionUC_HandleNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.UpdateStatusRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.UpdateStatusRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionUC_HandleNotification_Call) Return(err error) *MockTransactionUC_HandleNotification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionUC_HandleNotification_Call) RunAndReturn(run func(ctx context.Context, req *domain.UpdateStatusRequest) error) *MockTransactionUC_HandleNotification_Call {
	_c.Call.Return(run)
	return _c
}
